/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Y6gyY4ZpB1L
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { EventCardProps } from "../EventCard"
import { Fragment } from "react"

const events: EventCardProps[] = [
  {
    id: "1",
    title: "Fiesta de Verano",
    date: new Date(),
    description: "Ven a disfrutar de una noche de música, baile y diversión bajo las estrellas. Habrá comida, bebidas y mucha alegría.",
    map: "456 Oak St, Anytown USA",
    // image: "/placeholder.svg",
    //tickets: 100
  },
  {
    id: "2",
    title: "Fiesta de Verano",
    date: new Date(),
    description: "Ven a disfrutar de una noche de música, baile y diversión bajo las estrellas. Habrá comida, bebidas y mucha alegría.",
    map: "456 Oak St, Anytown USA",
    // image: "/placeholder.svg",
    //tickets: 100
  },
  {
    id: "3",
    title: "Fiesta de Verano",
    date: new Date(),
    description: "Ven a disfrutar de una noche de música, baile y diversión bajo las estrellas. Habrá comida, bebidas y mucha alegría.",
    map: "456 Oak St, Anytown USA",
    // image: "/placeholder.svg",
    //tickets: 100
  }
]

export function EventsPageComponent() {
  return (
    <div className="flex-1 overflow-auto bg-[#1a1a1a] page-inner">
      <div className="p-4 grid gap-4">
        <div className="flex items-center justify-between">
          <div className="text-2xl font-semibold">Próximos Eventos</div>
          <Link href="#" className="bg-[#333333] text-white px-4 py-2 rounded-md hover:bg-[#444444]" prefetch={false}>
            Crear Nuevo Evento
          </Link>
        </div>

        {
          events.map((event, index) => (
            <Fragment key={event.id}>
              <Card className="bg-[#222222] p-4 rounded-lg">
                <CardHeader>
                  <CardTitle>Noche de Cine</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-6">
                    <div className="flex flex-col items-start gap-4">
                      <img
                        src="/placeholder.svg"
                        alt="Event Image"
                        width={300}
                        height={200}
                        className="rounded-lg object-cover w-full max-w-[300px]"
                        style={{ aspectRatio: "300/200", objectFit: "cover" }}
                      />
                      <div className="flex-1">
                        <div className="text-lg font-medium">Noche de Cine</div>
                        <div className="text-sm text-[#aaa]">Viernes, 16 de junio a las 8:00 PM</div>
                        <div className="text-sm text-[#aaa] mt-2">
                          Únete a nosotros para una noche de películas y palomitas en nuestro cine comunitario. Disfruta de
                          una selección de clásicos y estrenos recientes en un ambiente acogedor.
                        </div>
                        <div className="flex items-center gap-4 mt-4">
                          <Link
                            href="#"
                            target="_blank"
                            className="flex items-center gap-2 text-sm text-[#aaa] hover:text-white"
                            prefetch={false}
                          >
                            <MapPinIcon className="w-5 h-5" />
                            Ver en el mapa
                          </Link>
                          <Button variant="outline" size="sm">
                            Reservar Boletos
                          </Button>
                        </div>
                      </div>
                    </div>
                    <Separator />
                    <div className="grid gap-2">
                      <div className="font-medium">Detalles del Evento</div>
                      <div className="grid sm:grid-cols-2 gap-4">
                        <div className="flex items-center gap-2">
                          <CalendarIcon className="w-5 h-5" />
                          <div>Viernes, 16 de junio</div>
                        </div>
                        <div className="flex items-center gap-2">
                          <ClockIcon className="w-5 h-5" />
                          <div>8:00 PM - 11:00 PM</div>
                        </div>
                        <div className="flex items-center gap-2">
                          <MapPinIcon className="w-5 h-5" />
                          <div>123 Main St, Anytown USA</div>
                        </div>
                        <div className="flex items-center gap-2">
                          <UsersIcon className="w-5 h-5" />
                          <div>Hasta 50 personas</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              {index < events.length - 1 && <Separator />}
            </Fragment>
          ))
        }
      </div>
    </div>
  )
}

function CalendarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function ClockIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function HomeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function MapPinIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}


function MenuIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function PlusIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function SettingsIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function UsersIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
